# Generated by Django 5.0.4 on 2024-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_core_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boost',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
